# Very nearly actions/starter-workflows' cmake.yml, but with a build matrix

name: Automatic Tests
on:
  - push
  - pull_request
jobs:
  build-main:
    strategy:
      matrix:
        config: [ "-O3 -s", "-Os -s", "-O0 -g" ]
        compiler: [ "gcc", "clang" ]
        example:
          - simple
          - simple-json
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: ${{github.workspace}}
      run: ${{matrix.compiler}} -Wall -Wextra -Werror ${{matrix.config}} -I. examples/${{matrix.example}}.c examples/lib.c -o example
    - name: Run
      working-directory: ${{github.workspace}}
      run: ./example >output
    - name: Compare
      working-directory: ${{github.workspace}}
      run: diff output examples/${{matrix.example}}.expected.txt
